#!/bin/bash
#SBATCH --account=laionize
#SBATCH --job-name=scalability_test
#SBATCH --partition=develbooster
#SBATCH --time=30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1     # Let torchrun handle the GPUs
#SBATCH --gpus-per-node=4
# SBATCH --cpus-per-task=48     # Commented out.
#SBATCH --output=./slurm-%j.out

#### This is a comment.
# SBATCH --output=./logs/slurm_logs/%j.out


# Usage:
#     sbatch pretrain_jsc.job

# For quick tests on max 4 nodes, max 2h walltime and internet connection: #SBATCH --partition=develbooster
# For more nodes and time: set #SBATCH --partition=booster

set -e  # Exit immediately on error

# -----------------------------
# MODEL TYPE
# -----------------------------
MODEL=gidd  # options: gidd, ar or mdlm


# -----------------------------
# SOFTWARE
# -----------------------------
# Don't load PyTorch. Install it from the packages
module purge
module load Stages/2025 GCCcore/.13.3.0 Python/3.12.3 NCCL/default-CUDA-12
export VENV_PATH="/p/project1/laionize/onutu2_juwelsbooster/gidd/.venv"
source $VENV_PATH/bin/activate

if [[ -n "$VIRTUAL_ENV" ]]; then
    echo "Virtual environment is active: $VIRTUAL_ENV"
else
    echo "No virtual environment active"
fi

# -----------------------------
# DISTRIBUTED
# -----------------------------
export MASTER_ADDR="$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)"
if [ "$SYSTEMNAME" = juwelsbooster ] \
       || [ "$SYSTEMNAME" = juwels ] \
       || [ "$SYSTEMNAME" = jurecadc ] \
       || [ "$SYSTEMNAME" = jusuf ]; then
    # Usage of InfiniBand interfance is not automatic.
    # To allow communication over InfiniBand cells on JSC machines append "i" to the hostname.
    MASTER_ADDR="$MASTER_ADDR"i
fi
export MASTER_PORT=39591

TOTAL_GPUS=$((SLURM_NNODES * SLURM_GPUS_PER_NODE))

# Prevent Gloo not being able to communicate.
export GLOO_SOCKET_IFNAME=ib0

# Code works without this as well
export NCCL_SOCKET_IFNAME=ib0


# Note from https://apps.fz-juelich.de/jsc/hps/juwels/gpu-computing.html#gpu-visibility-affinity
export CUDA_VISIBLE_DEVICES=0,1,2,3

# Found as example here: https://apps.fz-juelich.de/jsc/hps/juwels/batchsystem.html#writing-a-batch-script
# export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}    # error: libgomp: Invalid value for environment variable OMP_NUM_THREADS: 

DISTRIBUTED_ARGS=(
    --nproc-per-node $SLURM_GPUS_PER_NODE 
    --nnodes $SLURM_NNODES
)


# -----------------------------
# Logging
# -----------------------------
WDIR="/p/scratch/laionize/onutu2/logs"
TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")
JOB_NAME="1B-${MODEL}-fineweb-pu=0.0-${TOTAL_GPUS}gpu-${SLURM_NNODES}node-jsc-a100-8mbs-job${SLURM_JOB_ID}"
HYDRA_RUN_DIR=${WDIR}/${TIMESTAMP}_${JOB_NAME}
mkdir -p "$HYDRA_RUN_DIR"

{
    echo "Job started at: $(date)"
    echo "Job ID: ${SLURM_JOB_ID}"
    echo "GPU type: ${GPU_TYPE}"
    echo "GPUs per node: ${SLURM_GPUS_PER_NODE}"
    echo "Total nodes: ${SLURM_NNODES}"
    echo "Total GPUs: ${TOTAL_GPUS}"

    echo "Running on master node: ${MASTER_ADDR}"
    echo "Allocated nodes:"
    scontrol show hostnames $SLURM_JOB_NODELIST

} > "${HYDRA_RUN_DIR}/cluster_allocation.log"

echo "Cluster allocation info saved to ${HYDRA_RUN_DIR}/cluster_allocation.log"


# Offline wandb logging
export WANDB_MODE=offline

cd /p/project1/laionize/onutu2_juwelsbooster/gidd

# -----------------------------
# Launch training
# -----------------------------
# torchrun_jsc is a wrapper around torchrun for JSC
# env -u CUDA_VISIBLE_DEVICES unsets the environment variable
# torchrun_jsc ... -m gidd.train tells Python to run the specificed module (gidd.train) as a script
srun env -u CUDA_VISIBLE_DEVICES torchrun_jsc "${DISTRIBUTED_ARGS[@]}" \
    --rdzv_id=$SLURM_JOBID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
    --master_addr=$MASTER_ADDR \
    --master_port=$MASTER_PORT \
    -m gidd.train \
    --config-name=$MODEL \
    logging.run_name="'${JOB_NAME}'" \
    hydra.run.dir="'${HYDRA_RUN_DIR}'" \