#!/bin/bash
#SBATCH --account=aifac_l01_028
#SBATCH --job-name=scalability_test
#SBATCH --partition=boost_usr_prod
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1     # Let torchrun handle the GPUs
#SBATCH --cpus-per-task=32
#SBATCH --gpus-per-node=4
#SBATCH --output=/leonardo_scratch/large/userexternal/donutu00/logs/slurm_logs/%j.out

# Usage:
#     sbatch pretrain_lrnd.job

set -e  # Exit immediately on error


# -----------------------------
# MODEL CONFIGS
# -----------------------------
MODEL=gidd-pu0.0  # options: gidd-pu0.0, ar or mdlm
MODEL_SIZE=1B # options: 1B, small, base, tiny
DATASET=fineweb
MBS=8


# -----------------------------
# SOFTWARE
# -----------------------------
module purge
module load python/3.11.7 nccl/2.22.3-1--gcc--12.2.0-cuda-12.2-spack0.22
export VENV_PATH="/leonardo_work/AIFAC_L01_028/donutu/gidd/.venv"
source $VENV_PATH/bin/activate


# -----------------------------
# DISTRIBUTED TRAINING
# -----------------------------
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
export MASTER_PORT=39591

TOTAL_GPUS=$((SLURM_NNODES * SLURM_GPUS_PER_NODE))

DISTRIBUTED_ARGS=(
    --nproc-per-node $SLURM_GPUS_PER_NODE 
    --nnodes $SLURM_NNODES
)

# 1. Check if the nodes establish connection
# 2. Check if you see NCCL WARN NET/Socket : Socket failure, then you need to export NCCL_SOCKET_IFNAME=ib0
# 3. Check if you see something like (below). Then, you know that InfiniBand interface is used.
# jwb0117:378071:378216 [0] NCCL INFO Using network IB 
# jwb0117:378073:378219 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB [3]mlx5_3:1/IB [RO]; OOB ib0:10.13.23.95<0>
# export NCCL_DEBUG=INFO


# -----------------------------
# Logging
# -----------------------------
WDIR="/leonardo_scratch/large/userexternal/donutu00/logs"
TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")
JOB_NAME="${MODEL_SIZE}-${MODEL}-${DATASET}-${TOTAL_GPUS}gpu-${SLURM_NNODES}node-lnrd-a100-${MBS}mbs-job${SLURM_JOB_ID}"
HYDRA_RUN_DIR=${WDIR}/${TIMESTAMP}_${JOB_NAME}
mkdir -p "$HYDRA_RUN_DIR"

{
    echo "Job started at: $(date)"
    echo "Job ID: ${SLURM_JOB_ID}"
    echo "GPUs per node: ${SLURM_GPUS_PER_NODE}"
    echo "Total nodes: ${SLURM_NNODES}"
    echo "Total GPUs: ${TOTAL_GPUS}"

    echo "Running on master node: ${MASTER_ADDR}"
    echo "Allocated nodes:"
    scontrol show hostnames $SLURM_JOB_NODELIST

} > "${HYDRA_RUN_DIR}/cluster_allocation.log"

echo "Cluster allocation info saved to ${HYDRA_RUN_DIR}/cluster_allocation.log"

# Offline wandb logging
export WANDB_MODE=offline


# -----------------------------
# Launch training
# -----------------------------
srun torchrun "${DISTRIBUTED_ARGS[@]}" \
    --rdzv_id=$SLURM_JOBID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
    --master_addr=$MASTER_ADDR \
    --master_port=$MASTER_PORT \
    gidd/train.py \
    --config-name=$MODEL \
    logging.run_name="${JOB_NAME}" \
    hydra.run.dir="${HYDRA_RUN_DIR}" \
