#!/bin/bash
#SBATCH --account=aifac_l01_028
#SBATCH --job-name=scalability_test
#SBATCH --partition=boost_usr_prod
#SBATCH --qos=boost_qos_dbg
#SBATCH --time=30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1     # Let torchrun handle the GPUs
#SBATCH --cpus-per-task=32
#SBATCH --gpus-per-node=4
#SBATCH --output=/leonardo_scratch/large/userexternal/donutu00/gidd/slurm_logs/%j.out
#SBATCH --error=/leonardo_scratch/large/userexternal/donutu00/gidd/slurm_logs/%j.err

# Usage:
#     sbatch pretrain_lrdn.job

# For quick tests on max 2 nodes: #SBATCH --qos=boost_qos_dbg
# For large node numbers (> 64 nodes): add #SBATCH --qos=boost_qos_bprod

# Bash "strict mode" (see http://redsymbol.net/articles/unofficial-bash-strict-mode/)
set -euo pipefail


# -----------------------------
# SOFTWARE - SERVER SPECIFIC
# -----------------------------
module purge
module load python/3.11.7 nccl/2.22.3-1--gcc--12.2.0-cuda-12.2-spack0.22
export VENV_PATH="/leonardo_work/AIFAC_L01_028/donutu00/gidd/.venv"
source $VENV_PATH/bin/activate


# -----------------------------
# EXPERIMENT CONFIGS
# -----------------------------
WDIR="$SCRATCH/gidd" # Machine specific
MODEL=gidd      # options: gidd, gidd-pu0.2, gidd-pu0.1, ar or mdlm
MODEL_SIZE=1B     # options: 1B, small, base, tiny
DATASET=fineweb
MBS=2               
GBS=                 # Global batch size. If not set, it will be MBS * total gpus.    
SL=4096               # Sequence length. initial: 512, options: 1024, 2048, 4096
GAS=                 # Gradient accumulation steps.
TRAIN_STEPS=1000

# TODO: Add config for "tiny" model size
if [ "$MODEL_SIZE" == "small" ]; then
    N_PARAMS="0.17"
elif [ "$MODEL_SIZE" == "base" ]; then
    N_PARAMS="0.42"
elif [ "$MODEL_SIZE" == "1B" ]; then
    N_PARAMS="1.50"
else
    echo "Unknown MODEL_SIZE: $MODEL_SIZE"
    exit 1
fi


# -----------------------------
# DISTRIBUTED TRAINING
# -----------------------------
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
export MASTER_PORT=39591

if [ "$SLURM_JOB_PARTITION" == "gpu_h100" ]; then
    # Known issue on Snellius. NCCL sometimes hangs during initialization.
    # Workaround: set NCCL_SOCKET_IFNAME to the ethernet interface for initialization.
    echo "Using H100 partition on Snellius, setting NCCL_SOCKET_IFNAME to eno2np0"
    export NCCL_SOCKET_IFNAME="eno2np0"
    SERVER="SNLSh"
    export WANDB_MODE=online

elif [ "$SLURM_JOB_PARTITION" == "gpu_a100" ]; then
    echo "Using A100 partition on Snellius, setting NCCL_SOCKET_IFNAME to eno1np0"
    export NCCL_SOCKET_IFNAME="eno1np0"
    SERVER="SNLSa"
    export WANDB_MODE=online

# ${SYSTEMNAME:-} expans to an empty string if SYSTEMNAME is not set
elif [[ "${SYSTEMNAME:-}" == juwelsbooster ]]; then
    echo "Using Juwels booster partition, setting GLOO_SOCKET_IFNAME to ib0"
    # Prevent Gloo not being able to communicate.
    export GLOO_SOCKET_IFNAME=ib0
    # Code works without this as well
    # export NCCL_SOCKET_IFNAME=ib0
    SERVER="JSC"

    # Note from https://apps.fz-juelich.de/jsc/hps/juwels/gpu-computing.html#gpu-visibility-affinity
    export CUDA_VISIBLE_DEVICES=0,1,2,3

    # Found as example here: https://apps.fz-juelich.de/jsc/hps/juwels/batchsystem.html#writing-a-batch-script
    # export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}    # gives error: libgomp: Invalid value for environment variable OMP_NUM_THREADS: 

    export WANDB_MODE=offline

elif [[ "$SLURM_CLUSTER_NAME" = leonardo ]]; then
    echo "Using Leonardo booster partition"
    SERVER="LRDN"
    export WANDB_MODE=offline
fi 

TOTAL_GPUS=$((SLURM_NNODES * SLURM_GPUS_PER_NODE))

DISTRIBUTED_ARGS=(
    --nproc-per-node $SLURM_GPUS_PER_NODE 
    --nnodes $SLURM_NNODES
)

# 1. Check if the nodes establish connection
# 2. Check if you see NCCL WARN NET/Socket : Socket failure, then you need to export NCCL_SOCKET_IFNAME=ib0
# 3. Check if you see something like (below). Then, you know that InfiniBand interface is used.
# jwb0117:378071:378216 [0] NCCL INFO Using network IB 
# jwb0117:378073:378219 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB [3]mlx5_3:1/IB [RO]; OOB ib0:10.13.23.95<0>
export NCCL_DEBUG=INFO


# -----------------------------
# Logging
# -----------------------------
SL_NAME=""
GAS_NAME=""
if [ -n "$SL" ]; then
    SL_NAME="-${SL}sl"
fi
if [ -n "$GAS" ]; then
    GAS_NAME="-${GAS}gas"
fi

TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")
JOB_NAME="${SERVER}-${SLURM_JOB_ID}-${N_PARAMS}B-${TOTAL_GPUS}gpu-${MBS}mbs-${DATASET}-${MODEL}${SL_NAME}${GAS_NAME}"
HYDRA_RUN_DIR=${WDIR}/${TIMESTAMP}_${JOB_NAME}
mkdir -p "$HYDRA_RUN_DIR"

{
    echo "Job started at: $(date)"
    echo "Job ID: ${SLURM_JOB_ID}"
    echo "GPU type: ${SLURM_JOB_PARTITION}"
    echo "GPUs per node: ${SLURM_GPUS_PER_NODE}"
    echo "Total nodes: ${SLURM_NNODES}"
    echo "Total GPUs: ${TOTAL_GPUS}"

    echo "Running on master node: ${MASTER_ADDR}"
    echo "Allocated nodes:"
    scontrol show hostnames $SLURM_JOB_NODELIST

} > "${HYDRA_RUN_DIR}/cluster_allocation.log"
echo "Cluster allocation info saved to ${HYDRA_RUN_DIR}/cluster_allocation.log"

# -----------------------------
# Launch training - SERVER SPECIFIC
# -----------------------------
export PYTHONPATH="$WORK/$USER/gidd:${PYTHONPATH:-}"
cd $WORK/$USER/gidd


srun torchrun "${DISTRIBUTED_ARGS[@]}" \
    --rdzv_id=$SLURM_JOBID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
    --master_addr=$MASTER_ADDR \
    --master_port=$MASTER_PORT \
    gidd/train.py \
    --config-name=$MODEL \
    data.dataset_name=/leonardo_work/AIFAC_L01_028/donutu00/raw \
    data.tokenizer_name=/leonardo_work/AIFAC_L01_028/donutu00/tokenizers/models--gpt2/snapshots/607a30d783dfa663caf39e06633721c8d4cfcd7e \
    data.cache_dir=/leonardo_scratch/large/userexternal/donutu00/.cache \
    model.max_seq_len=$SL \
    logging.wandb_project=gidd-gidd \
    logging.run_name="${JOB_NAME}" \
    model=$MODEL_SIZE \
    training.train_batch_size=$MBS \
    training.eval_batch_size=$MBS \
    training.num_train_steps=$TRAIN_STEPS \
    hydra.run.dir="${HYDRA_RUN_DIR}" \