#!/bin/bash
#SBATCH --job-name=1B-gidd-fineweb-4gpu-1node-snls-h100-8bs-fsdp
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --partition=gpu_h100
#SBATCH --time=1:00:00
#SBATCH --output=slurm_logs/%x-%j.out
#SBATCH --error=slurm_logs/%x-%j.err

# Usage:
#     sbatch train_gidd_snls.job
#

set -e  # Exit immediately on error

# Activate environment
module purge
module load 2024 Python/3.12.3-GCCcore-13.3.0 NCCL/2.22.3-GCCcore-13.3.0-CUDA-12.6.0
export VENV_PATH=".venv"
source $VENV_PATH/bin/activate

# Distributed training
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
export MASTER_PORT=39591

# Print in job file
echo "Job submission date: $(date)"

NODE_COUNT=$(scontrol show hostnames $SLURM_JOB_NODELIST | wc -l)
echo "Number of nodes allocated: $NODE_COUNT"

TOTAL_GPUS=$((SLURM_NNODES * SLURM_GPUS_PER_NODE))
echo "Number of GPUs allocated: $TOTAL_GPUS"

echo "MASTER_ADDR: $MASTER_ADDR"
echo "Running on node: $(hostname)"

DISTRIBUTED_ARGS=(
    --nproc-per-node $SLURM_GPUS_PER_NODE 
    --nnodes $SLURM_NNODES
)

# Set NCCL environment variables
# Set the correct NCCL_SOCKET_IFNAME based on the partition
if [ "$SLURM_JOB_PARTITION" == "gpu_h100" ]; then
    echo "Using H100 partition, setting NCCL_SOCKET_IFNAME to eno2np0"
    export NCCL_SOCKET_IFNAME="eno2np0"
else
    echo "Using A100 or other partition, setting NCCL_SOCKET_IFNAME to eno1np0"
    export NCCL_SOCKET_IFNAME="eno1np0"
fi
export NCCL_P2P_DISABLE=1

#export NCCL_DEBUG=INFO # for debugging

# files are deleted after 40 days
export WDIR="/scratch-shared/avettoruzzo/gidd_logs"

# Launch training
srun torchrun "${DISTRIBUTED_ARGS[@]}" \
    --rdzv_id=$SLURM_JOBID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
    --master_addr=$MASTER_ADDR \
    --master_port=$MASTER_PORT \
    gidd/train.py \
        --config-name=gidd \
        data.dataset_name: /projects/0/prjs1502/datasets/FineWeb/raw \
        data.tokenizer_name: gpt2 \
        data.cache_dir: /scratch-shared/avettoruzzo/datasets \
        logging.wandb_project=gidd-gidd \
        logging.run_name="$SLURM_JOB_NAME" \
        hydra.job.name="$SLURM_JOB_NAME"