#!/bin/bash
#SBATCH --job-name=1B-ar-fineweb-64gpu-16node-jsc-a100-8bs-fsdp
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --cpus-per-task=48
#SBATCH --time=01:00:00
#SBATCH --account=laionize
#SBATCH --partition=booster
#SBATCH --output=/p/project/laionize/vettoruzzo1_juwelsbooster/gidd/slurm_logs/%x-%j.out
#SBATCH --error=/p/project/laionize/vettoruzzo1_juwelsbooster/gidd/slurm_logs/%x-%j.err

# For quick tests on max 4 nodes, max 2h walltime and internet connection: #SBATCH --partition=develbooster
# For more nodes and time: set #SBATCH --partition=booster

set -e  # Exit immediately on error

# Activate environment
module purge #module Stages/2025 remains loaded by default. If you want to unload it use `module --force purge`
module load GCCcore/.13.3.0 Python/3.12.3 NCCL/default-CUDA-12
export VENV_PATH="/p/project/laionize/vettoruzzo1_juwelsbooster/gidd/.venv"
source $VENV_PATH/bin/activate

# Set directories
curr_file="$(scontrol show job "$SLURM_JOB_ID" | grep '^[[:space:]]*Command=' | head -n 1 | cut -d '=' -f 2-)"
curr_dir="$(dirname "$curr_file")"
echo "Current file: $curr_file"
echo "Current directory: $curr_dir"
# Add outer 'gidd/' directory to PYTHONPATH so imports like 'from gidd.models...' work
export PYTHONPATH="/p/project1/laionize/vettoruzzo1_juwelsbooster/gidd:$PYTHONPATH" 
echo "Python path: $PYTHONPATH"

# Distributed training
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
# Allow communication over InfiniBand cells.
# adding “i” to hostname is crucial, otherwise compute nodes will not be able to communicate
export MASTER_ADDR="$MASTER_ADDR"i
export MASTER_PORT=54123
# Prevent NCCL not figuring out how to initialize.
export NCCL_SOCKET_IFNAME=ib0
# Prevent Gloo not being able to communicate.
export GLOO_SOCKET_IFNAME=ib0

# Print in job file
echo "Job submission date: $(date)"

NODE_COUNT=$(scontrol show hostnames $SLURM_JOB_NODELIST | wc -l)
echo "Number of nodes allocated: $NODE_COUNT"

echo "MASTER_ADDR: $MASTER_ADDR"
echo "Running on node: $(hostname)"

DISTRIBUTED_ARGS=(
    --nproc-per-node $SLURM_GPUS_PER_NODE 
    --nnodes $SLURM_NNODES
)

# STILL A NECESSARY WORKAROUND TO MAKE ALL GPUs on the nodes visible
export CUDA_VISIBLE_DEVICES=0,1,2,3

export WDIR="/p/project/laionize/vettoruzzo1_juwelsbooster/gidd_logs"

# to run wandb in offline mode
export WANDB_MODE=offline

cd /p/project/laionize/vettoruzzo1_juwelsbooster/gidd

# Launch training
srun env -u CUDA_VISIBLE_DEVICES torchrun_jsc "${DISTRIBUTED_ARGS[@]}" \
  --rdzv_id=$SLURM_JOBID \
  --rdzv_backend=c10d \
  --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
  --master_addr=$MASTER_ADDR \
  --master_port=$MASTER_PORT \
  -m gidd.train \
    --config-name=ar \
    logging.wandb_project=gidd-ar \
    logging.run_name="$SLURM_JOB_NAME" \
    hydra.job.name="$SLURM_JOB_NAME"